-- Early warning alerts
-- Generated by earlyWarningRunner (every 15 min) from multi-signal convergence.
-- Alert types: 'tone_shift', 'volume_spike', 'firms_anomaly', 'event_acceleration',
--              'displacement_spike', 'narrative_divergence', 'convergence'
CREATE TABLE IF NOT EXISTS alerts (
  id           SERIAL PRIMARY KEY,
  alert_type   TEXT NOT NULL,
  severity     TEXT NOT NULL,                  -- 'critical', 'elevated', 'watch'
  country      TEXT,
  conflict_id  TEXT REFERENCES conflicts(id) ON DELETE SET NULL,
  title        TEXT NOT NULL,
  description  TEXT,
  signal_data  JSONB,                          -- raw signal values that triggered this alert
  resolved     BOOLEAN DEFAULT FALSE,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_created  ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved ON alerts(resolved);
CREATE INDEX IF NOT EXISTS idx_alerts_country  ON alerts(country);
CREATE INDEX IF NOT EXISTS idx_alerts_type     ON alerts(alert_type);

-- User watchlists
-- Entities a user has pinned for elevated monitoring and custom alerts.
CREATE TABLE IF NOT EXISTS watchlists (
  id               SERIAL PRIMARY KEY,
  user_id          TEXT NOT NULL DEFAULT 'default',  -- future: auth system
  entity_type      TEXT NOT NULL,                    -- 'country', 'actor', 'conflict', 'region'
  entity_id        TEXT NOT NULL,                    -- country name, actor ID, conflict ID, or bbox
  alert_threshold  JSONB,                            -- custom thresholds per metric
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_watchlists_user   ON watchlists(user_id);
CREATE INDEX IF NOT EXISTS idx_watchlists_entity ON watchlists(entity_type, entity_id);
